languageCode = "en-us"
title = "c6p - log"
theme = "book"

#[server]
#  [[server.headers]]
#    for = "/**.html"
#    [server.headers.values]
#      Content-Security-Policy = "default-src 'none'; base-uri 'self'; manifest-src 'self'; connect-src 'self'; font-src 'self' https://cdn.jsdelivr.net; img-src 'self' data:; script-src-elem 'sha256-aECzxYUJ57J5H6YymaVqtppSpIqD2Z9YAIAZfd/2xMY=' 'sha256-bhmJoIC3YIYXV97TU9ErG8rOMntLK8xVVOwL2u9BqoA=' 'sha256-MktN23nRzohmT1JNxPQ0B9CzVW6psOCbvJ20j9YxAxA=' 'sha256-ncNI9OXOS5Ek4tzVYiOMmN/KKCPZ6V0Cpv2P/zHntiA=' 'sha256-OBZ1TAxtlr9xf3a+8VMnoX0v39PPCWCsN6DfNkKio/I=' 'sha256-OyJHvRcZHaRR6Ig73ppxF4QXk8HzvfgTprRWkulCkfY=' 'sha256-vlTmGAKWgBGxhfPI6r2aGtY9v9YXdRdwDc1bQkegBh4=' 'strict-dynamic'; script-src 'self' 'unsafe-inline' https:; style-src 'self' 'unsafe-inline' https://cdn.jsdelivr.net; object-src 'none'"
#      Referrer-Policy = "strict-origin"
#      X-Content-Type-Options = "nosniff"
#      X-Frame-Options = "DENY"
#      X-XSS-Protection = "1; mode=block"

[outputs]
home = ["HTML", "HEADERS"]

# remove .{ext} from text/netlify
[mediaTypes."text/netlify"]
suffixes = [""]
delimiter = ""

[outputFormats.HEADERS]
mediatype = "text/netlify"
baseName = "_headers"
isPlainText = true
notAlternative = true

[params]
BookTheme = "dark"

[markup]
  [markup.highlight]
      style = "monokai"
  [markup.goldmark]
    [markup.goldmark.extensions]
      footnote = true
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.parser]
      [markup.goldmark.parser.attribute]
        block = true
        title = true